    
// THIS CODE WAS GENERATED BY JTRANSLATE - DO NOT EDIT BY HAND
class TranslationKeys{

  // yesContinue = Yes, continue
  static const String yesContinue = "yesContinue";
  // noGoBack = No, go back
  static const String noGoBack = "noGoBack";
  // cancel = Cancel
  static const String cancel = "cancel";

}