    
// THIS CODE WAS GENERATED BY JTRANSLATE - DO NOT EDIT BY HAND
class TranslationKeys{

  // YouHavePushedTheButtonThisManyTimes = You have pushed the button this many times
  static const String youHavePushedTheButtonThisManyTimes = "YouHavePushedTheButtonThisManyTimes";
  // FlutterDemoPage = Flutter Demo Page
  static const String flutterDemoPage = "FlutterDemoPage";
  // FlutterDemo = Flutter Demo
  static const String flutterDemo = "FlutterDemo";
  // OnlyInEnglish = This Text only exists in english
  static const String onlyInEnglish = "OnlyInEnglish";

}