targets:
  jtranslate:jtranslate:
    builders:
      jtranslate|jsonToCodeBuilder:
        enabled: True

builders:
  jsonToCodeBuilder:
    import: 'package:jtranslate/jtranslate_generator.dart'
    builder_factories: ['jsonToCodeBuilder']
    build_extensions:
      .json:
        - .g.dart
    build_to: source
    auto_apply: dependents
